name: pokedex
channels:
- anaconda
dependencies:
- python==3.7.9
- pip==20.3.1
- pip:
    - jupyter==1.0.0
    - ipykernel==6.16.2
    - tensorflow==2.10.0
    - imutils==0.5.4
    - matplotlib==3.5.2
    - opencv-python==4.6.0.66
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - numpy==1.21.6
